### ISSUE TITLE
GCC 4.8.5 Build failure, different inttypes.h?

### ISSUE THREAD

**Issue by h1z1** [mikesart/gpuvis#9]
I get this with the latest git :

> src/stlini.cpp: In member function ‘void CIniFile::PutUint64(const char*, uint64_t, const char*)’:
> src/stlini.cpp:325:41: error: expected ‘)’ before ‘PRIx64’
>      snprintf( buf, sizeof( buf ), "0x%" PRIx64, value );
> 

Not sure where the problem is (RH or porting?)  but I couldn't build on gcc 4.8.5 / CentOS 7 without manually adding definitions for :

```
#define PRId64 "lld"
#define PRIx64 "llx"
#define PRIu64 "llu"
#define PRIo64 "llo"
```

to src/stlini.cpp

Including inttypes.h itself didn't work as they are defined differently.

```
/* The ISO C99 standard specifies that these macros must only be
   defined if explicitly requested.  */

#if !defined __cplusplus || defined __STDC_FORMAT_MACROS

# if __WORDSIZE == 64
#  define __PRI64_PREFIX        "l"
#  define __PRIPTR_PREFIX       "l"
# else
#  define __PRI64_PREFIX        "ll"
#  define __PRIPTR_PREFIX
# endif

# define PRIx64		__PRI64_PREFIX "x"

```

**Comment by mikesart** [comment]
If you do a:
```#define __STDC_FORMAT_MACROS```
before the #include <inttypes.h>, does it work?

**Comment by h1z1** [comment]
Bunch of warnings .. And this :)

```
Linking _release/gpuvis...
_release/src/gpuvis.o: In function `unzip_first_file':
build/mikesart/gpuvis.git/src/gpuvis.cpp:510: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

```

.. but it does indeed.   Thanks Mike.

**Comment by mikesart** [comment]
Should be fixed with change 81b84c1.

I'll look at cleaning the release build warnings up (they don't happen in debug builds). They're in imgui and stb, so have to get fixes pushed over there.

Also need to fix tmpnam but it has to work on Mac and Windows, so I don't think it's as easy as just switching to mkstemp.

Thanks h1z1.
